vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    


    mappings:
        employes_images:
            uri_prefix: '%employes_images%'
            upload_destination: '%kernel.project_dir%/public%employes_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
    
    
            